name: ItemsAdderContentsSync
version: '${version}'
main: com.epicplayera10.itemsaddercontentssync.ItemsAdderContentsSync
api-version: 1.19
authors: [EpicPlayerA10]
website: https://fanthstudios.pl

loadbefore:
  - ItemsAdder
  - ModelEngine
  - CosmeticsCore
  - MythicMobs
  - MCPets
